Update screenshots and config

diff --git a/.github/workflows/NativePipeline.yml b/.github/workflows/NativePipeline.yml
--- a/.github/workflows/NativePipeline.yml
+++ b/.github/workflows/NativePipeline.yml
@@ -232,175 +232,175 @@ jobs:
         with:
           name: mda
           path: automation.mda
-  android-bundle:
-    needs: [project, mendix-version]
-    runs-on: ubuntu-22.04
-    container:
-      image: ghcr.io/mendix/native-widgets/mxbuild:${{ needs.mendix-version.outputs.mendix_version }}
-      credentials:
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
-    steps:
-      - name: "Check out code"
-        uses: actions/checkout@v4
-      - name: "Download deployment package"
-        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
-        with:
-          name: mda
-      - name: "Create Android bundle"
-        uses: ./.github/actions/create-native-bundle
-        with:
-          platform: android
-          mda-file: automation.mda
-  ios-bundle:
-    needs: [project, mendix-version]
-    runs-on: ubuntu-22.04
-    container:
-      image: ghcr.io/mendix/native-widgets/mxbuild:${{ needs.mendix-version.outputs.mendix_version }}
-      credentials:
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
-    steps:
-      - name: "Check out code"
-        uses: actions/checkout@v4
-      - name: "Download project MDA file"
-        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
-        with:
-          name: mda
-      - name: "Create iOS bundle"
-        uses: ./.github/actions/create-native-bundle
-        with:
-          platform: ios
-          mda-file: automation.mda
-  android-app:
-    needs: [android-bundle]
-    runs-on: ubuntu-22.04
-    steps:
-      - name: "Check out Native Template for Native Components Test Project"
-        uses: actions/checkout@v4
-        with:
-          repository: mendix/native-template
-          ref: ${{ github.event.inputs.nt_branch || 'master' }}
-          path: native-template
-      - name: "Check out code"
-        uses: actions/checkout@v4
-        with:
-          path: native-widgets
-      - name: "Download Android bundle and assets"
-        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
-        with:
-          name: android-bundle
-          path: bundles/android
-      - name: "Set up Node"
-        uses: actions/setup-node@v4
-        with:
-          node-version-file: native-template/.nvmrc
-          cache: npm
-          cache-dependency-path: native-template/package-lock.json
-      - name: "Cache Android Build"
-        uses: actions/cache@v3
-        with:
-          path: native-template/android/app/build
-          key: ${{ runner.os }}-android-build-${{ hashFiles('native-template/android/app/src/**/*.java', 'native-template/android/app/src/**/*.kt', 'native-template/android/app/build.gradle') }}
-          restore-keys: |
-            ${{ runner.os }}-android-build-
-      - name: "Copy files to the right location"
-        run: |
-          mv bundles/android/index.android.bundle native-template/android/app/src/main/assets/index.android.bundle
-          cp -r bundles/android/assets/* native-template/android/app/src/main/res/
-          mv native-widgets/configs/e2e/config.json native-template
-          mv native-widgets/configs/e2e/google-services.json native-template/android/app
-          node native-widgets/scripts/test/add-native-dependencies.js
-      - name: "Install dependencies"
-        working-directory: native-template
-        run: npm i
-      - name: "Setup JDK "
-        uses: actions/setup-java@v4
-        with:
-          java-version: 21
-          distribution: temurin
-          cache: gradle
+  # android-bundle:
+  #   needs: [project, mendix-version]
+  #   runs-on: ubuntu-22.04
+  #   container:
+  #     image: ghcr.io/mendix/native-widgets/mxbuild:${{ needs.mendix-version.outputs.mendix_version }}
+  #     credentials:
+  #       username: ${{ github.actor }}
+  #       password: ${{ secrets.GITHUB_TOKEN }}
+  #   steps:
+  #     - name: "Check out code"
+  #       uses: actions/checkout@v4
+  #     - name: "Download deployment package"
+  #       uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
+  #       with:
+  #         name: mda
+  #     - name: "Create Android bundle"
+  #       uses: ./.github/actions/create-native-bundle
+  #       with:
+  #         platform: android
+  #         mda-file: automation.mda
+  # ios-bundle:
+  #   needs: [project, mendix-version]
+  #   runs-on: ubuntu-22.04
+  #   container:
+  #     image: ghcr.io/mendix/native-widgets/mxbuild:${{ needs.mendix-version.outputs.mendix_version }}
+  #     credentials:
+  #       username: ${{ github.actor }}
+  #       password: ${{ secrets.GITHUB_TOKEN }}
+  #   steps:
+  #     - name: "Check out code"
+  #       uses: actions/checkout@v4
+  #     - name: "Download project MDA file"
+  #       uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
+  #       with:
+  #         name: mda
+  #     - name: "Create iOS bundle"
+  #       uses: ./.github/actions/create-native-bundle
+  #       with:
+  #         platform: ios
+  #         mda-file: automation.mda
+  # android-app:
+  #   needs: [android-bundle]
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - name: "Check out Native Template for Native Components Test Project"
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: mendix/native-template
+  #         ref: ${{ github.event.inputs.nt_branch || 'master' }}
+  #         path: native-template
+  #     - name: "Check out code"
+  #       uses: actions/checkout@v4
+  #       with:
+  #         path: native-widgets
+  #     - name: "Download Android bundle and assets"
+  #       uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
+  #       with:
+  #         name: android-bundle
+  #         path: bundles/android
+  #     - name: "Set up Node"
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: native-template/.nvmrc
+  #         cache: npm
+  #         cache-dependency-path: native-template/package-lock.json
+  #     - name: "Cache Android Build"
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: native-template/android/app/build
+  #         key: ${{ runner.os }}-android-build-${{ hashFiles('native-template/android/app/src/**/*.java', 'native-template/android/app/src/**/*.kt', 'native-template/android/app/build.gradle') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-android-build-
+  #     - name: "Copy files to the right location"
+  #       run: |
+  #         mv bundles/android/index.android.bundle native-template/android/app/src/main/assets/index.android.bundle
+  #         cp -r bundles/android/assets/* native-template/android/app/src/main/res/
+  #         mv native-widgets/configs/e2e/config.json native-template
+  #         mv native-widgets/configs/e2e/google-services.json native-template/android/app
+  #         node native-widgets/scripts/test/add-native-dependencies.js
+  #     - name: "Install dependencies"
+  #       working-directory: native-template
+  #       run: npm i
+  #     - name: "Setup JDK "
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         java-version: 21
+  #         distribution: temurin
+  #         cache: gradle
 
-      - name: "Build Android app"
-        working-directory: native-template/android
-        run: |
-          ./gradlew assembleAppstoreDebug assembleAppstoreDebugAndroidTest
-          if [ $? -ne 0 ]; then
-            echo "Build failed!"
-            exit 1
-          fi
-      - name: "List APK files"
-        run: |
-          echo "Listing APK files in the output directory:"
-          ls -R native-template/android/app/build/outputs/apk/
-      - name: "Archive Android app"
-        uses: actions/upload-artifact@v4
-        with:
-          name: android-app
-          path: native-template/android/app/build/outputs/apk/**/*.apk
-  ios-app:
-    needs: [ios-bundle]
-    runs-on: macos-13
-    steps:
-      - name: "Check out Native Template for Native Components Test Project"
-        uses: actions/checkout@v4
-        with:
-          repository: mendix/native-template
-          ref: ${{ github.event.inputs.nt_branch || 'master' }}
-          path: native-template
-      - name: "Check out code"
-        uses: actions/checkout@v4
-        with:
-          path: native-widgets
-      - name: "Download iOS bundle and assets"
-        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
-        with:
-          name: ios-bundle
-          path: bundles/ios
-      - name: "Set up Node"
-        uses: actions/setup-node@v4
-        with:
-          node-version-file: native-template/.nvmrc
-          cache: npm
-          cache-dependency-path: native-template/package-lock.json
-      - name: "Cache iOS Build"
-        uses: actions/cache@v3
-        with:
-          path: native-template/ios/build
-          key: ${{ runner.os }}-ios-build-${{ hashFiles('native-template/ios/**/*.swift', 'native-template/ios/**/*.h', 'native-template/ios/Podfile.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-ios-build-
-      - name: "Copy files to the right location"
-        run: |
-          mv bundles/ios/index.ios.bundle native-template/ios/Bundle/index.ios.bundle
-          mv bundles/ios/assets/assets native-template/ios/Bundle/
-          mv native-widgets/configs/e2e/config.json native-template
-          node native-widgets/scripts/test/add-native-dependencies.js
-      - name: "Install Node dependencies"
-        working-directory: native-template
-        run: npm i
+  #     - name: "Build Android app"
+  #       working-directory: native-template/android
+  #       run: |
+  #         ./gradlew assembleAppstoreDebug assembleAppstoreDebugAndroidTest
+  #         if [ $? -ne 0 ]; then
+  #           echo "Build failed!"
+  #           exit 1
+  #         fi
+  #     - name: "List APK files"
+  #       run: |
+  #         echo "Listing APK files in the output directory:"
+  #         ls -R native-template/android/app/build/outputs/apk/
+  #     - name: "Archive Android app"
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: android-app
+  #         path: native-template/android/app/build/outputs/apk/**/*.apk
+  # ios-app:
+  #   needs: [ios-bundle]
+  #   runs-on: macos-13
+  #   steps:
+  #     - name: "Check out Native Template for Native Components Test Project"
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: mendix/native-template
+  #         ref: ${{ github.event.inputs.nt_branch || 'master' }}
+  #         path: native-template
+  #     - name: "Check out code"
+  #       uses: actions/checkout@v4
+  #       with:
+  #         path: native-widgets
+  #     - name: "Download iOS bundle and assets"
+  #       uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
+  #       with:
+  #         name: ios-bundle
+  #         path: bundles/ios
+  #     - name: "Set up Node"
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: native-template/.nvmrc
+  #         cache: npm
+  #         cache-dependency-path: native-template/package-lock.json
+  #     - name: "Cache iOS Build"
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: native-template/ios/build
+  #         key: ${{ runner.os }}-ios-build-${{ hashFiles('native-template/ios/**/*.swift', 'native-template/ios/**/*.h', 'native-template/ios/Podfile.lock') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-ios-build-
+  #     - name: "Copy files to the right location"
+  #       run: |
+  #         mv bundles/ios/index.ios.bundle native-template/ios/Bundle/index.ios.bundle
+  #         mv bundles/ios/assets/assets native-template/ios/Bundle/
+  #         mv native-widgets/configs/e2e/config.json native-template
+  #         node native-widgets/scripts/test/add-native-dependencies.js
+  #     - name: "Install Node dependencies"
+  #       working-directory: native-template
+  #       run: npm i
 
-      - name: "Setup Pods cache"
-        uses: actions/cache@v3
-        with:
-          path: native-template/Pods
-          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-pods-
-      - name: "Install Pod dependencies"
-        working-directory: native-template/ios
-        run: pod install
-      - name: "Build iOS app"
-        working-directory: native-template/ios
-        run: xcodebuild -workspace NativeTemplate.xcworkspace -scheme nativeTemplate -configuration Debug -sdk iphonesimulator -derivedDataPath build ONLY_ACTIVE_ARCH=YES VALID_ARCHS="i386 x86_64"
-      - name: "Archive iOS app"
-        uses: actions/upload-artifact@v4
-        with:
-          name: ios-app
-          path: native-template/ios/build/Build/Products/**/*.app
+  #     - name: "Setup Pods cache"
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: native-template/Pods
+  #         key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-pods-
+  #     - name: "Install Pod dependencies"
+  #       working-directory: native-template/ios
+  #       run: pod install
+  #     - name: "Build iOS app"
+  #       working-directory: native-template/ios
+  #       run: xcodebuild -workspace NativeTemplate.xcworkspace -scheme nativeTemplate -configuration Debug -sdk iphonesimulator -derivedDataPath build ONLY_ACTIVE_ARCH=YES VALID_ARCHS="i386 x86_64"
+  #     - name: "Archive iOS app"
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: ios-app
+  #         path: native-template/ios/build/Build/Products/**/*.app
 
   android-tests:
-    needs: [scope, mendix-version, project, android-app]
+    needs: [scope, mendix-version, project]
     runs-on: ubuntu-22.04
     timeout-minutes: 720
     steps:
@@ -477,7 +477,7 @@ jobs:
           path: ${{ github.workspace }}/maestro/images/actual/android/**/*.png
           if-no-files-found: ignore
   ios-tests:
-    needs: [scope, mendix-version, project, ios-app]
+    needs: [scope, mendix-version, project]
     runs-on: macos-15
     timeout-minutes: 720
     steps:
