Fix ios tests

diff --git a/.github/workflows/NativePipeline.yml b/.github/workflows/NativePipeline.yml
--- a/.github/workflows/NativePipeline.yml
+++ b/.github/workflows/NativePipeline.yml
@@ -497,13 +497,12 @@ jobs:
         uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
         with:
           name: mda
-      # Used when new xCode version of simulator should be created
-      # - name: Update Xcode
-      #   run: sudo xcode-select --switch /Applications/Xcode_14.0.1.app
+      
       - name: "Clean detox framework cache"
         run: npx detox clean-framework-cache
       - name: "Build detox framework cache"
         run: npx detox build-framework-cache
+      
       - name: "Start runtime"
         uses: ./.github/actions/start-runtime
         with:
@@ -520,17 +519,66 @@ jobs:
           find ios-app -type d -iname "*.app" -exec cp -R {} detox/apps/ \;
       - name: Install Detox Dependencies
         run: |
-          brew tap wix/brew
+          brew tap wix/brew 
           brew install applesimutils
+      
       - name: Check available runtimes
         run: xcrun simctl list runtimes
       - name: Check avialble device types
         run: xcrun simctl list devicetypes
-      # - name: Create iOS 16.0 simulator for iPhone 14
-      #   run: xcrun simctl create "iPhone 14" com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-16-0
+      # - name: Create iOS 18.1 simulator for iPhone 16
+      #   run: xcrun simctl create "iPhone 16" com.apple.CoreSimulator.SimDeviceType.iPhone-16 com.apple.CoreSimulator.SimRuntime.iOS-18-1
       - name: List supported iOS devices
         run: applesimutils --list
+
+      # - name: Boot Simulator
+      #   run: xcrun simctl boot "iPhone 15"
+      # - name: Wait for Simulator to Boot
+      #   run: |
+      #     while ! xcrun simctl list | grep "Booted"; do
+      #       echo "Waiting for simulator to boot..."
+      #       sleep 5
+      #     done
+
+      # - name: "Check if iOS app exists in detox/apps"
+      #   run: |
+      #     APP_PATH="detox/apps/NativeTemplate.app"
+      #     if [ ! -d "$APP_PATH" ]; then
+      #       echo "App not found at path: $APP_PATH"
+      #     else
+      #       echo "App found at path: $APP_PATH"
+      #     fi
+
+      # - name: "Check if iOS app exists in full BINARY_PATH"
+      #   run: |
+      #     BINARY_PATH="/Users/runner/work/native-widgets/native-widgets/detox/apps/NativeTemplate.app"
+      #     echo "BINARY_PATH=$BINARY_PATH" >> $GITHUB_ENV
+      #     if [ ! -d "$BINARY_PATH" ]; then
+      #       echo "App not found at path: $BINARY_PATH"
+      #       echo "Listing contents of the apps directory:"
+      #       ls -R /Users/runner/work/native-widgets/native-widgets/detox/apps # List contents of the apps directory for debugging
+      #     else
+      #       echo "App found at path: $BINARY_PATH"
+      #     fi
+  
+      # - name: "List contents of the app bundle"
+      #   run: |
+      #     echo "Listing contents of the app bundle at $BINARY_PATH:"
+      #     ls -R "$BINARY_PATH"
+  
+      # - name: "Install app on simulator"
+      #   run: |
+      #     SIMULATOR_ID=$(xcrun simctl list devices | grep "iPhone 15" | grep "Booted" | awk -F '[()]' '{print $2}')
+      #     if [ -z "$SIMULATOR_ID" ]; then
+      #       echo "No booted simulator found for iPhone 15."
+      #       exit 1
+      #     fi
+      #     echo "Installing app on simulator with ID: $SIMULATOR_ID"
+      #     xcrun simctl install "$SIMULATOR_ID" "$BINARY_PATH"
+
       - name: "Run tests"
+        env:
+          DETOX_LOGLEVEL: trace
         run: yarn workspaces foreach ${{ needs.scope.outputs.scope }} run test:e2e:ios
       - name: "Archive runtime logs"
         uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
