Adding maestro config

diff --git a/.github/workflows/NativePipeline.yml b/.github/workflows/NativePipeline.yml
--- a/.github/workflows/NativePipeline.yml
+++ b/.github/workflows/NativePipeline.yml
@@ -59,7 +59,7 @@ on:
           - video-player-native
           - web-view-native
 
-# Disable trigger on pull request for now
+# Disable trigger on every push to pull request for now
 # pull_request:
 # #   branches: [master]
 
@@ -338,7 +338,7 @@ jobs:
           path: native-template/android/app/build/outputs/apk/**/*.apk
   ios-app:
     needs: [ios-bundle]
-    runs-on: macos-14
+    runs-on: macos-13
     steps:
       - name: "Check out Native Template for Native Components Test Project"
         uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
@@ -509,7 +509,17 @@ jobs:
             adb push "detox/apps/app-appstore-debug-androidTest.apk" "/data/local/tmp/detox/Test.apk"
             adb shell pm install -r -g -t /data/local/tmp/detox/Application.apk 2>/dev/null
             adb shell pm install -r -g -t /data/local/tmp/detox/Test.apk 2>/dev/null
-            yarn workspaces foreach ${{ needs.scope.outputs.scope }} run test:e2e:android
+
+      - name: "Install Maestro"
+        run: |
+          curl -Ls "https://get.maestro.dev" | bash
+
+      - name: "Make run_maestro.sh Executable"
+        run: chmod +x maestro/run_maestro.sh
+
+      - name: "Run Maestro Script"
+        run: maestro/run_maestro.sh android
+
       - name: "Archive runtime logs"
         uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
         if: always()
@@ -535,7 +545,7 @@ jobs:
           if-no-files-found: ignore
   ios-tests:
     needs: [scope, mendix-version, project, ios-app]
-    runs-on: macos-14
+    runs-on: macos-13
     steps:
       - name: "Check out code"
         uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
@@ -588,12 +598,12 @@ jobs:
       #   run: xcrun simctl list runtimes
       # - name: Check available device types
       #   run: xcrun simctl list devicetypes
-      - name: Create iOS 17.5 simulator for iPhone 15
-        run: xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-5
+      - name: Create iOS 16.4 simulator for iPhone 14
+        run: xcrun simctl create "iPhone 14" com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-16-4
       # - name: List supported iOS devices
       #   run: applesimutils --list
       - name: Boot Simulator
-        run: xcrun simctl boot "iPhone 15"
+        run: xcrun simctl boot "iPhone 14"
       - name: Wait for Simulator to Boot
         run: |
           while ! xcrun simctl list | grep "Booted"; do
@@ -629,30 +639,35 @@ jobs:
             echo "App found at path: $BINARY_PATH"
           fi
 
-      - name: "Install app on simulator"
+      # - name: "Install app on simulator"
+      #   run: |
+      #     SIMULATOR_ID=$(xcrun simctl list devices | grep "iPhone 15" | grep "Booted" | awk -F '[()]' '{print $2}')
+      #     if [ -z "$SIMULATOR_ID" ]; then
+      #       echo "No booted simulator found for iPhone 15."
+      #       exit 1
+      #     fi
+      #     echo "Checking if app exists at path: $BINARY_PATH"
+      #     if [ ! -d "$BINARY_PATH" ]; then
+      #       echo "Error: App not found at path: $BINARY_PATH"
+      #       echo "Listing contents of the directory:"
+      #       ls -R "$(dirname "$BINARY_PATH")" # List contents of the parent directory
+      #       exit 1
+      #     fi
+      #     echo "Installing app on simulator with ID: $SIMULATOR_ID"
+      #     xcrun simctl install "$SIMULATOR_ID" "$BINARY_PATH"
+      - name: "Install Maestro"
         run: |
-          SIMULATOR_ID=$(xcrun simctl list devices | grep "iPhone 15" | grep "Booted" | awk -F '[()]' '{print $2}')
-          if [ -z "$SIMULATOR_ID" ]; then
-            echo "No booted simulator found for iPhone 15."
-            exit 1
-          fi
-          echo "Checking if app exists at path: $BINARY_PATH"
-          if [ ! -d "$BINARY_PATH" ]; then
-            echo "Error: App not found at path: $BINARY_PATH"
-            echo "Listing contents of the directory:"
-            ls -R "$(dirname "$BINARY_PATH")" # List contents of the parent directory
-            exit 1
-          fi
-          echo "Installing app on simulator with ID: $SIMULATOR_ID"
-          xcrun simctl install "$SIMULATOR_ID" "$BINARY_PATH"
+          curl -Ls "https://get.maestro.dev" | bash
 
       - name: "Wait for app to be ready"
         run: sleep 10
 
-      - name: "Run tests"
-        env:
-          DETOX_LOGLEVEL: trace
-        run: yarn workspaces foreach ${{ needs.scope.outputs.scope }} run test:e2e:ios
+      - name: "Make run_maestro.sh Executable"
+        run: chmod +x maestro/run_maestro.sh
+
+      - name: "Run Maestro Script"
+        run: maestro/run_maestro.sh ios
+
       - name: "Archive runtime logs"
         uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
         if: always()
